spark.wmu.staging: &staging
  stage: staging
  configFile: ~/.ssh/config
  multiplexing: true
  deploy_path: /var/www/html/wmu.spark-staging.dev
  shared_files:
    - .env

spark.wmu.staging.local:
  <<: *staging
  stage: staging-local
  local: true

spark.wmu.production:
  stage: production
  configFile: ~/.ssh/config
  multiplexing: true
  deploy_path: /var/www/html/goalscaling.com
  shared_files:
    - .env